## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName

## HCloud csi-driver image version
## ref: https://hub.docker.com/r/hetznercloud/hcloud-csi-driver/tags
##
image:
  registry: docker.io
  repository: hetznercloud/hcloud-csi-driver
  tag: 1.5.3
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName
  pullSecrets: []

## String to partially override hcloud-csi.fullname template (will maintain the release name)
# nameOverride:

## String to fully override hcloud-csi.fullname template
# fullnameOverride:

hcloudToken:
storageClass:
  default: false
  name: "hcloud-csi"

## Allow the customization of the kubelet path for non standart kubernetes distros like microk8s and k0s
##
kubeletPath: "/var/lib/kubelet"

## priorityClassName
## ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass
##
priorityClassName: "system-cluster-critical"

## Prometheus Exporter / Metrics
##
metrics:
  enabled: false

  ## Prometheus exporter service parameters
  ##
  service:
    ## Prometheus exporter service type
    ##
    type: ClusterIP
    ## Prometheus exporter port
    ##
    port: 9189
    ## Annotations for the Prometheus exporter service
    ##
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "{{ .Values.metrics.service.port }}"

   ## Prometheus Operator ServiceMonitor configuration
  ##
  serviceMonitor:
    enabled: false
    ## Namespace in which Prometheus is running
    ##
    # namespace: monitoring
    ## Interval at which metrics should be scraped.
    ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint
    ##
    interval: 60s
    ## Timeout after which the scrape is ended
    ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint
    ##
    # scrapeTimeout: 10s
    ## ServiceMonitor selector labels
    ## ref: https://github.com/bitnami/charts/tree/master/bitnami/prometheus-operator#prometheus-configuration
    ##
    # selector:
    #   prometheus: my-prometheus
  
  prometheusRule:
    enabled: false
    additionalLabels: {}
    namespace: ''
    rules: []