apiVersion: v2
name: hcloud-ccm
version: v1.8.1
appVersion: v1.8.1
kubeVersion: ">=v1.16.0"
description: Kubernetes cloud-controller-manager for Hetzner Cloud
home: https://github.com/hetznercloud/hcloud-cloud-controller-manager
keywords:
- cloud-controller-manager
- hcloud
sources:
- https://github.com/hetznercloud/hcloud-cloud-controller-manager
maintainers:
- name: QuHive
  email: dev@quhive.dev
icon: https://avatars2.githubusercontent.com/u/22154697?s=200&v=4
engine: gotpl
annotations:
  catalog.cattle.io/certified: quhive
  catalog.cattle.io/namespace: kube-system
  catalog.cattle.io/release-name: hcloud-ccm
  catalog.cattle.io/display-name: "HCloud CCM"