## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName

## HCloud cloud-controller-manager image version
## ref: https://hub.docker.com/r/hetznercloud/hcloud-cloud-controller-manager/tags
##
image:
  registry: docker.io
  repository: hetznercloud/hcloud-cloud-controller-manager
  tag: v1.8.1
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName

## String to partially override hcloud-ccm.fullname template (will maintain the release name)
# nameOverride:

## String to fully override hcloud-ccm.fullname template
# fullnameOverride:

hcloudToken:
hcloudNetworks:
  enabled: false
  ## name:
hcloudLoadBalancers:
  enabled: false
  ## defaultLocation:
  ## defaultUsePrivateIp

## Replica count
##
replicas: 1

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    memory: 100Mi
    cpu: 50m
