
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hcloud-ccm.fullname" . }}
  labels: {{ include "hcloud-ccm.labels" . | nindent 4 }}
type: Opaque
stringData:
  hcloud-token: {{ .Values.hcloudToken }}