apiVersion: v2
name: cert-manager-crd
version: 1.1.0
appVersion: v1.1.0
description: cert-manager is a x509 certificate manager for Kubernetes.
home: https://github.com/jetstack/cert-manager
keywords:
- cert-manager
- certificates
sources:
- https://github.com/quhive/charts/tree/master/charts/cert-manager
- https://github.com/jetstack/cert-manager
maintainers:
- name: QuHive
  email: dev@quhive.dev
- name: munnerz
  email: james@jetstack.io
icon: https://raw.githubusercontent.com/jetstack/cert-manager/master/logo/logo.png
engine: gotpl
annotations:
  catalog.cattle.io/certified: quhive
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: cert-manager-system
  catalog.cattle.io/release-name: cert-manager-crd