apiVersion: v2
name: external-dns
version: 0.7.5
appVersion: v0.7.5
description: ExternalDNS is a Kubernetes addon that configures public DNS servers with information about exposed Kubernetes services to make them discoverable.
home: https://github.com/kubernetes-sigs/external-dns/
keywords:
- external-dns
- network
- dns
sources:
- https://github.com/quhive/charts/tree/master/charts/external-dns
maintainers:
- name: QuHive
  email: dev@quhive.dev
icon: https://github.com/kubernetes-sigs/external-dns/raw/master/img/external-dns.png
engine: gotpl
annotations:
  catalog.cattle.io/auto-install: external-dns-crd=match
  catalog.cattle.io/certified: quhive
  catalog.cattle.io/namespace: external-dns-system
  catalog.cattle.io/release-name: external-dns
  catalog.cattle.io/display-name: "ExternalDNS"