{{- if .Values.global.podSecurityPolicy.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "webhook.fullname" . }}-psp
  labels: {{ include "webhook.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "webhook.fullname" . }}-psp
subjects:
  - kind: ServiceAccount
    name: {{ template "webhook.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}