apiVersion: v1
kind: Service
metadata:
  name: {{ template "webhook.fullname" . }}
  labels: {{ include "webhook.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: {{ .Values.webhook.securePort }}
  selector: {{ include "webhook.labels" . | nindent 4 }}