{{- if .Values.ingressShim.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.ingressShim.defaultIssuerName }}
  labels: {{ include "cert-manager.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.clusterIssuer.type "SelfSigned" }}
  selfSigned: {}
  {{- else if eq .Values.clusterIssuer.type "ACME" }}
  acme:
    email: {{ .Values.clusterIssuer.acme.email }}
    {{- if eq .Values.clusterIssuer.acme.endpoint "Production" }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- end }}
    privateKeySecretRef:
      name: {{ .Values.ingressShim.defaultIssuerName }}
    solvers:
    {{- if eq .Values.clusterIssuer.acme.challengeType "HTTP01" }}
    - http01:
       ingress:
         class: {{ .Values.clusterIssuer.acme.http01.ingressClass }}
    {{- else if eq .Values.clusterIssuer.acme.challengeType "DNS01" }}
    - dns01:
        {{- if eq .Values.clusterIssuer.acme.dns01.dnsProvider "CloudFlare" }}
        cloudflare:
          email: {{ .Values.clusterIssuer.acme.dns01.cloudflare.email }}
          apiTokenSecretRef:
            name: {{ .Values.ingressShim.defaultIssuerName }}
            {{- if eq .Values.clusterIssuer.acme.dns01.cloudflare.authType "Key" }}
            key: api-key
            {{- else if eq .Values.clusterIssuer.acme.dns01.cloudflare.authType "Token" }}
            key: api-token
            {{- end }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }}