{{- if and .Values.ingressShim.enabled (eq .Values.clusterIssuer.type "ACME") (eq .Values.clusterIssuer.acme.challengeType "DNS01") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingressShim.defaultIssuerName }}
  labels: {{ include "cert-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if eq .Values.clusterIssuer.acme.dns01.dnsProvider "CloudFlare" }}
  {{- if eq .Values.clusterIssuer.acme.dns01.cloudflare.authType "Key" }}
  api-key: {{ .Values.clusterIssuer.acme.dns01.cloudflare.key }}
  {{- else if eq .Values.clusterIssuer.acme.dns01.cloudflare.authType "Token" }}
  api-token: {{ .Values.clusterIssuer.acme.dns01.cloudflare.token }}
  {{- end }}
  {{- end }}
{{- end }}