---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: hcloud-csi
  name: hcloud-csi-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: hcloud-csi
  template:
    metadata:
      labels:
        app: hcloud-csi
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: instance.hetzner.cloud/is-root-server
                    operator: NotIn
                    values:
                      - "true"
      tolerations:
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
      priorityClassName: {{ .Values.priorityClassName }}
      containers:
        - name: csi-node-driver-registrar
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --kubelet-registration-path={{ .Values.hcloud.node.kubeletPath | default "/var/lib/kubelet" }}/plugins/csi.hetzner.cloud/socket
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 10m
              memory: 32Mi
          volumeMounts:
            - name: plugin-dir
              mountPath: /run/csi
            - name: registration-dir
              mountPath: /registration
        - name: hcloud-csi-driver
          image: "{{ template "image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/hcloud-csi-driver-node
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 10m
              memory: 32Mi
          env:
            - name: CSI_ENDPOINT
              value: unix:///run/csi/socket
            - name: METRICS_ENDPOINT
              value: 0.0.0.0:9189
            - name: ENABLE_METRICS
              value: "true"
          securityContext:
            privileged: true
          ports:
            - containerPort: 9189
              name: metrics
            - containerPort: 9808
              name: healthz
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            periodSeconds: 2
            timeoutSeconds: 3
          volumeMounts:
            - name: kubelet-dir
              mountPath: {{ .Values.hcloud.node.kubeletPath | default "/var/lib/kubelet" }}
              mountPropagation: Bidirectional
            - name: plugin-dir
              mountPath: /run/csi
            - name: device-dir
              mountPath: /dev
        - name: liveness-probe
          image: k8s.gcr.io/sig-storage/livenessprobe:v2.3.0
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 10m
              memory: 32Mi
          volumeMounts:
            - name: plugin-dir
              mountPath: /run/csi
      volumes:
        - name: kubelet-dir
          hostPath:
            path: {{ .Values.hcloud.node.kubeletPath | default "/var/lib/kubelet" }}
            type: Directory
        - name: plugin-dir
          hostPath:
            path: {{ .Values.hcloud.node.kubeletPath | default "/var/lib/kubelet" }}/plugins/csi.hetzner.cloud/
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: {{ .Values.hcloud.node.kubeletPath | default "/var/lib/kubelet" }}/plugins_registry/
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory
---

