apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hcloud-csi.fullname" . }}
  labels: {{ include "hcloud-csi.labels" . | nindent 4 }}
type: Opaque
stringData:
  hcloud-token: {{ .Values.hcloudToken }}
