---
apiVersion: v1
kind: Service
metadata:
  name: hcloud-csi-controller-metrics
  namespace: kube-system
spec:
  ports:
    - name: metrics
      port: 9189
      targetPort: metrics
  selector:
    app: hcloud-csi-controller
---
apiVersion: v1
kind: Service
metadata:
  name: hcloud-csi-node-metrics
  namespace: kube-system
spec:
  ports:
    - name: metrics
      port: 9189
      targetPort: metrics
  selector:
    app: hcloud-csi
---

