{{- if .Values.hcloud.storageClass.enabled }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.hcloud.storageClass.name }}
  namespace: kube-system
  annotations:
    {{- if .Values.hcloud.storageClass.default }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end}}
provisioner: csi.hetzner.cloud
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: {{ .Values.hcloud.storageClass.reclaimPolicy | default "Delete" }}
---
{{- end }}
