name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.9.4

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Release Chart
        uses: helm/chart-releaser-action@v1.1.0
        with:
          charts_repo_url: https://quhive.github.io/charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"